### ISSUE TITLE
$newzonename is undefined in virtual_feature.pl

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-mailrelay#1]
In this line, $newzonename is undefine, and it isn't referenced anywhere else in the file or module, so surely some sort of bug. I can't figure out what it's trying to do, so not sure how to fix it.

```
my @recs = &bind8::read_zone_file($fn, $newzonename);
```

https://github.com/virtualmin/virtualmin-mailrelay/blob/master/virtual_feature.pl#L351

**Comment by jcameron** [comment]
Fixed!
